From HoTT Require Import Basics Types Truncations.Core.
From HoTT.WildCat Require Import Core.
Require Import Spaces.Finite.Fin.
Require Import Algebra.Rings.Ring Algebra.Rings.CRing Algebra.Rings.Ideal.

Local Open Scope ring_scope.
Local Open Scope mc_scope.
Local Open Scope predicate_scope.

(** * Bézout rings and principal ideal domains

    Constructive definitions following Christensen and Flaten, Definitions
    2.6.2-2.6.3, with Lemma 2.6.4 (translating Lombardi and Quitté). *)

(** Divisibility: [a] divides [b] if [b] is a multiple of [a]. *)
Definition rng_divides {R : CRing} (a b : R) : Type
  := merely { c : R & b = c * a }.

(** An element is regular if multiplication by it is injective. *)
Definition IsRegular {R : CRing} (a : R) : Type
  := forall x y : R, a * x = a * y -> x = y.

(** An integral domain: every element is zero or regular. *)
Class IsIntegralDomain (R : CRing) : Type
  := intdom_zero_or_regular : forall x : R, (x = 0) + IsRegular x.

(** A greatest common divisor of [x] and [y] is a common divisor divisible by
    every common divisor. *)
Definition IsGcd {R : CRing} (x y g : R) : Type
  := (rng_divides g x) * (rng_divides g y)
     * (forall z : R, rng_divides z x -> rng_divides z y -> rng_divides z g).

(** A Bézout ring: every pair has a Bézout combination that is a gcd. *)
Class IsBezoutRing (R : CRing) : Type
  := bezout_relation : forall x y : R,
       merely { u : R & { v : R & IsGcd x y (u * x + v * y) } }.

(** A Bézout domain is a Bézout ring that is an integral domain. *)
Class IsBezoutDomain (R : CRing) : Type := {
  bezoutdomain_bezout :: IsBezoutRing R ;
  bezoutdomain_domain :: IsIntegralDomain R
}.

(** A principal ideal domain: a Bézout domain in which every ascending chain of
    ideals merely has two equal consecutive terms. *)
Class IsPID (R : CRing) : Type := {
  pid_bezout :: IsBezoutDomain R ;
  pid_noetherian : forall I : nat -> Ideal R,
    (forall n, I n ⊆ I (S n)) -> merely { n : nat & I n = I (S n) }
}.

(** An ideal is principal if it is merely generated by a single element. *)
Definition IsPrincipal {R : Ring} (I : Ideal R) : Type
  := merely { a : R & ideal_generated_finite (fun _ : Fin 1 => a) = I }.

(** ** Divisibility algebra *)

Definition rng_divides_refl {R : CRing} (a : R) : rng_divides a a.
Proof.
  apply tr; exists 1; exact (rng_mult_one_l a)^.
Defined.

Definition rng_divides_trans {R : CRing} {a b c : R}
  (p : rng_divides a b) (q : rng_divides b c) : rng_divides a c.
Proof.
  strip_truncations; destruct p as [u pu], q as [v pv].
  apply tr; exists (v * u).
  exact (pv @ ap (fun w => v * w) pu @ rng_mult_assoc v u a).
Defined.

Definition rng_divides_mul_l {R : CRing} {a b : R} (r : R)
  (p : rng_divides a b) : rng_divides a (r * b).
Proof.
  strip_truncations; destruct p as [u pu].
  apply tr; exists (r * u).
  exact (ap (fun w => r * w) pu @ rng_mult_assoc r u a).
Defined.

Definition rng_divides_plus {R : CRing} {d a b : R}
  (pa : rng_divides d a) (pb : rng_divides d b) : rng_divides d (a + b).
Proof.
  strip_truncations; destruct pa as [c1 p1], pb as [c2 p2].
  apply tr; exists (c1 + c2).
  exact (ap011 (+) p1 p2 @ (rng_dist_r c1 c2 d)^).
Defined.

(** ** A finitely generated ideal of a Bézout ring is principal *)

(** A gcd of the [X i] lying in the ideal they generate and dividing each. *)
Definition finite_gcd {R : CRing} `{IsBezoutRing R}
  : forall (n : nat) (X : Fin n -> R),
    merely { g : R
           & ((forall i, rng_divides g (X i)) * ideal_generated_finite X g)%type }.
Proof.
  induction n as [|n IH]; intro X.
  - apply tr; exists 0; split.
    + intro i; destruct i.
    + apply ideal_in_zero.
  - pose proof (IH (fun i => X (inl i))) as IH'.
    strip_truncations; destruct IH' as [a' [hdiv' hin']].
    pose proof (bezout_relation a' (X (inr tt))) as hb.
    strip_truncations; destruct hb as [u [v hgcd]].
    destruct hgcd as [[gda' gdlast] _].
    apply tr; exists (u * a' + v * X (inr tt)); split.
    + intro j; destruct j as [i | t].
      * exact (rng_divides_trans gda' (hdiv' i)).
      * destruct t; exact gdlast.
    + napply ideal_in_plus.
      { rapply isleftideal.
        exact (ideal_generated_rec
                 (X := hfiber (fun i => X (inl i)))
                 (I := ideal_generated_finite X)
                 (fun r hf => tr (igt_in (inl hf.1; hf.2))) a' (tr hin')). }
      rapply isleftideal.
      exact (tr (igt_in (inr tt; idpath))).
Defined.

(** A finitely generated ideal of a Bézout ring is principal. *)
Definition isprincipal_finite_bezout `{Univalence} {R : CRing} `{IsBezoutRing R}
  {n : nat} (X : Fin n -> R)
  : IsPrincipal (ideal_generated_finite X).
Proof.
  pose proof (finite_gcd n X) as hg.
  strip_truncations; destruct hg as [g [gdiv gin]].
  apply tr; exists g.
  apply equiv_path_ideal; split.
  - napply (ideal_generated_rec (I := ideal_generated_finite X)).
    intros r hf.
    exact (transport (ideal_generated_finite X) hf.2 gin).
  - napply (ideal_generated_rec (I := ideal_generated_finite (fun _ : Fin 1 => g))).
    intros r hf.
    pose proof (gdiv hf.1) as hd; strip_truncations; destruct hd as [c pc].
    apply tr.
    exact (transport (ideal_generated_type _) (pc^ @ hf.2)
             (igt_mul_l (r := c) (igt_in (fin_zero; idpath)))).
Defined.
