Require Export WildCat.Core.
Require Export WildCat.Equiv.
Require Export WildCat.UnitCat.
Require Export WildCat.EmptyCat.
Require Export WildCat.Opposite.
Require Export WildCat.Type.
Require Export WildCat.Induced.
Require Export WildCat.FunctorCat.
Require Export WildCat.Yoneda.
Require Export WildCat.Prod.
Require Export WildCat.Sum.
