(** * Notations for natural transformations *)
Require HoTT.Categories.NaturalTransformation.Composition.
Require HoTT.Categories.NaturalTransformation.Dual.
Require HoTT.Categories.NaturalTransformation.Identity.
Require HoTT.Categories.NaturalTransformation.Prod.
Require HoTT.Categories.NaturalTransformation.Sum.

Include NaturalTransformation.Composition.NaturalTransformationCompositionNotations.
Include NaturalTransformation.Dual.NaturalTransformationDualNotations.
Include NaturalTransformation.Identity.NaturalTransformationIdentityNotations.
Include NaturalTransformation.Prod.NaturalTransformationProdNotations.
Include NaturalTransformation.Sum.NaturalTransformationSumNotations.
