Require NaturalTransformation.Composition.
Require NaturalTransformation.Duals.
Require NaturalTransformation.Identity.
Require NaturalTransformation.Sum.

Include NaturalTransformation.Composition.NaturalTransformationCompositionNotations.
Include NaturalTransformation.Duals.NaturalTransformationDualsNotations.
Include NaturalTransformation.Identity.NaturalTransformationIdentityNotations.
Include NaturalTransformation.Sum.NaturalTransformationSumNotations.
